version: '3.8'    # https://docs.docker.com/compose/ -- version docker compose
services:       # déclaration of services
  php-apache:   #first service php with apache server
    build:     #build from dockerfile
      dockerfile: Dockerfile
    #configuration of server
    ports:
      - 80:80
    volumes:
      - type: bind          #mount/sharing of src 
        source: ./src
        target: /var/www/html
      - type: bind          #sharing server configuration
        source: ./apache2/apache2.conf
        target: /etc/apache2/apache2.conf
    env_file:   #access to environment sql variables 
      - .env
    depends_on: #dependency bdd
      - mysql
  mysql: #second service
    image: mysql  
    #configuration
    ports:
      - 3307:3306
    env_file:     #access to environment sql variables 
      - .env
    volumes:
      - type: volume
        source: php-contact-vol
        target: /var/lib/mysql
  mailhog:    #third service mail
      image: mailhog/mailhog:v1.0.0
      ports:
        - "1025:1025"
        - "8025:8025"  #access on browser
volumes: #volume creation
  php-contact-vol: