version: '3.8'    # https://docs.docker.com/compose/ -- version docker compose
services:       # déclaration des services
  php-apache:   #nom du premier service
    build:     #build à partir du dockerfile
      dockerfile: Dockerfile
    #configuration
    ports:
      - 80:80
    volumes:
      - type: bind          #partage du dossier src 
        source: ./src
        target: /var/www/html
      - type: bind          #partage du fichier de configuration serveur 
        source: ./apache2/apache2.conf
        target: /etc/apache2/apache2.conf
    env_file:   #acces aux variables environment sql
      - .env
    depends_on: #dépendance à la base de données
      - mysql
  mysql: #nom du deuxième service
    image: mysql  
    #configuration
    ports:
      - 3307:3306
    env_file:     #acces aux variables environment sql
      - .env
    volumes:
      - type: volume
        source: php-contact-vol
        target: /var/lib/mysql
volumes: #creation du volume
  php-contact-vol: